[package]
name = "aoc"
version = "0.1.0"
authors = ["jari"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fstrings = "0.2.3"

[[bin]]
name = "day1"
path = "src/day1.rs"